CREATE DATABASE Cust0
GO

USE DATABASE Cust0;
GO


CREATE TABLE tipoUsuario(
idTipoUsuario TINYINT PRIMARY KEY IDENTITY (1,1),
nomeTipoUsuario VARCHAR(12) NOT NULL
);

CREATE TABLE Usuario(
idUsuario TINYINT PRIMARY KEY IDENTITY (1,1),
idTipoUsuario TINYINT FOREIGN KEY REFERENCES tipoUsuario(idTipoUsuario),
email VARCHAR(50) NOT NULL,
senha VARCHAR(30) NOT NULL
);

CREATE TABLE Cliente(
idCliente TINYINT PRIMARY KEY IDENTITY (1,1),
idUsuario TINYINT FOREIGN KEY REFERENCES Usuario(idUsuario),
nome VARCHAR(50) NOT NULL,
cpf VARCHAR(12) NOT NULL
);

CREATE TABLE Estado(
idEstado TINYINT PRIMARY KEY IDENTITY (1,1),
nomeEstado VARCHAR(40) NOT NULL
);

CREATE TABLE Endereco(
idEndereco TINYINT PRIMARY KEY IDENTITY (1,1),
idEstado TINYINT FOREIGN KEY REFERENCES Estado(idEstado),
cep VARCHAR(10) NOT NULL,
titulo VARCHAR(74) NOT NULL
);
